# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aac695383084645b46086a3d5d6efd61d517cb5377854ba1c1c3c0f2636e9f17577ab66afa444d16e0b6d813c4fe904f55f0dad97e4131e4d3e19286480e1d2c

test:
  secret_key_base: 7373517a63f992d7e03f02fff2ec7e72f331c47d0d811a7cf84bb670c0a67b26d16638e32b8a9c0f679376a7ac7d81914056cc62883f1ce3ff4590876dd65617

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
